[workspace]
members = ["workspace/*"]

[workspace.dependencies]
cortex-m = "0.7.7"
cortex-m-rt = "0.7.5"
cortex-m-semihosting = "0.5.0"
stm32f1xx-hal = { version = "0.10.0", features = ["stm32f103", "rt", "medium"] }
panic-halt = "1.0.0"
nb = "1.1.0"
