[package]
name = "vertex_from_storage"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu.workspace = true
pollster.workspace = true
async-channel = "2.3.1"
image = "0.25.5"
bytemuck = { version = "1.20.0", features = ["derive"] }
