[package]
name = "c04-hittable"
version = "0.1.0"
edition = "2021"

[dependencies]
glam.workspace = true
env_logger.workspace = true
indicatif.workspace = true
indicatif-log-bridge.workspace = true
log.workspace = true
